"""ExportManager for serializing BrewStanza reports to various formats."""

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from rich.prompt import Confirm

from brewstanza.analyzer.storage import StorageAnalyzer, StorageReport


class ExportManager:
    """Manages exporting storage reports to JSON, Brewfile, and other formats."""

    @staticmethod
    def to_json(report: StorageReport | None) -> str:
        """
        Serialize a StorageReport to JSON format with timestamp.

        The snapshot includes totals, human-readable sizes, and a per-item
        breakdown sorted by size descending.

        Args:
            report: The storage report to serialize. If None, produces a
                minimal empty snapshot (used in tests / dry-run scenarios).

        Returns:
            JSON string with full inventory snapshot and ISO 8601 timestamp.
        """
        if report is None:
            data: dict[str, Any] = {
                "timestamp": datetime.now().isoformat(),
                "homebrew_total_bytes": 0,
                "homebrew_total_human": "0.0 B",
                "apps_total_bytes": 0,
                "apps_total_human": "0.0 B",
                "combined_total_bytes": 0,
                "combined_total_human": "0.0 B",
                "items": [],
            }
            return json.dumps(data, indent=2)

        items = [
            {
                "name": item["name"],
                "type": item["type"],
                "size_bytes": item["size"],
                "size_human": StorageAnalyzer.format_size(item["size"]),
                "percentage": round(item["percentage"], 2),
            }
            for item in report.get("items", [])
        ]

        data = {
            "timestamp": datetime.now().isoformat(),
            "homebrew_total_bytes": report["homebrew_total"],
            "homebrew_total_human": StorageAnalyzer.format_size(report["homebrew_total"]),
            "apps_total_bytes": report["apps_total"],
            "apps_total_human": StorageAnalyzer.format_size(report["apps_total"]),
            "combined_total_bytes": report["combined_total"],
            "combined_total_human": StorageAnalyzer.format_size(report["combined_total"]),
            "items": items,
        }
        return json.dumps(data, indent=2)

    @staticmethod
    def to_brewfile(packages: list[dict[str, Any]]) -> str:
        """
        Serialize homebrew packages to standard Brewfile format.

        Formulae are emitted as ``brew "name"`` lines and casks as
        ``cask "name"`` lines, sorted alphabetically within each group.
        A header comment with the generation timestamp is included.

        Args:
            packages: List of package dicts.  Each dict must have at least
                ``"name"`` (str) and ``"type"`` (``"formula"`` or ``"cask"``).

        Returns:
            Brewfile-formatted string compatible with ``brew bundle install``.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines = [
            "# Brewfile generated by BrewStanza",
            f"# Generated at: {timestamp}",
            "",
        ]

        formulae = sorted(
            [p for p in packages if p.get("type") != "cask"],
            key=lambda p: str(p.get("name", "")).lower(),
        )
        casks = sorted(
            [p for p in packages if p.get("type") == "cask"],
            key=lambda p: str(p.get("name", "")).lower(),
        )

        if formulae:
            lines.append("# Formulae")
            for pkg in formulae:
                lines.append(f'brew "{pkg["name"]}"')
            lines.append("")

        if casks:
            lines.append("# Casks")
            for pkg in casks:
                lines.append(f'cask "{pkg["name"]}"')
            lines.append("")

        return "\n".join(lines)

    @staticmethod
    def write_file(content: str, path: Path, overwrite: bool = False) -> None:
        """
        Write exported content to a file with optional overwrite confirmation.

        Args:
            content: The content to write.
            path: Destination file path.
            overwrite: If False and the file already exists, prompt the user
                interactively before overwriting.  If True, overwrite silently.
        """
        if path.exists() and not overwrite:
            if not Confirm.ask(f"File {path} already exists. Overwrite?"):
                return

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
